name: Workflow 2

on:
  issues:
    types: [opened]

jobs:
  show_event_details:
    runs-on: ubuntu-latest

    steps:
      - name: Print event details
        run: echo '${{ toJson(github.event) }}'